added properties for who made last change
lblod/app-contactgegevens-loket pull request #45
Opened 2024-06-24 15:01 UTC by YJouhar47

https://binnenland.atlassian.net/browse/CLBV-709

2024-06-25 10:26 UTC, aliokan commented on config/resources/domain.json
> +          "predicate": "skos:prefLabel"
**Question:** Why do you want to display `skos:prefLabel` in both properties? I'm not certain that it's supported by `mu-cl-ressource`.

2024-06-25 10:37 UTC, mirdono commented on config/resources/domain.json
> +          "predicate": "skos:prefLabel"
@aliokan I **think** a better way of modelling this would be to add a relation to the relevant organization instead of these two values. Something along the lines of the following (where `ext:modifiedBy` is just an example predicate):
```
"modifiedBy": {
    "predicate:"  "ext:modifiedBy",
    "target": "organization",
    "cardinality": "one",
}
```
In the frontend you can than retrieve the correct organization's name and classification for displaying. This does come with two assumptions:
- you can determine the organization of the current user based on the session information; and
- users have read access to the names and classifications of other organizations.

2024-06-27 18:22 UTC, aliokan requested changes
@YJouhar47 I agree with @mirdono comment https://github.com/lblod/app-contactgegevens-loket/pull/45#discussion_r1652509755

2024-06-27 18:23 UTC, aliokan commented on config/resources/domain.json
> +          "predicate": "skos:prefLabel"
Good point, save the editor URI is more robust

2024-07-04 14:57 UTC, mirdono approved these changes

2024-07-04 15:19 UTC, merged